// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface ChecksumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Checksum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>map&lt;string, string&gt; data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, string&gt; data = 2;</code>
   */
  boolean containsData(String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getData();
  /**
   * <code>map&lt;string, string&gt; data = 2;</code>
   */
  java.util.Map<String, String>
  getDataMap();
  /**
   * <code>map&lt;string, string&gt; data = 2;</code>
   */

  String getDataOrDefault(String key, String defaultValue);
  /**
   * <code>map&lt;string, string&gt; data = 2;</code>
   */

  String getDataOrThrow(String key);

  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */
  int getExtendInfoCount();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */
  boolean containsExtendInfo(String key);
  /**
   * Use {@link #getExtendInfoMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getExtendInfo();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */
  java.util.Map<String, String>
  getExtendInfoMap();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */

  String getExtendInfoOrDefault(String key, String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */

  String getExtendInfoOrThrow(String key);
}
