// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface ChecksumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Checksum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>map&lt;string, bytes&gt; data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, bytes&gt; data = 2;</code>
   */
  boolean containsData(String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @Deprecated
  java.util.Map<String, com.google.protobuf.ByteString>
  getData();
  /**
   * <code>map&lt;string, bytes&gt; data = 2;</code>
   */
  java.util.Map<String, com.google.protobuf.ByteString>
  getDataMap();
  /**
   * <code>map&lt;string, bytes&gt; data = 2;</code>
   */

  com.google.protobuf.ByteString getDataOrDefault(String key,
		  com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; data = 2;</code>
   */

  com.google.protobuf.ByteString getDataOrThrow(String key);
}
