// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public final class Distro {
  private Distro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Load_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Load_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Merge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Merge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Merge_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Merge_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Checksum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Checksum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Checksum_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Checksum_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Query_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Query_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Values_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Values_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Values_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Values_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Distro.proto\"(\n\006Record\022\014\n\004data\030\001 \001(\014\022\020" +
      "\n\010checkSum\030\002 \001(\t\"\006\n\004Load\"|\n\005Merge\022\r\n\005gro" +
      "up\030\001 \001(\t\022\016\n\006origin\030\002 \001(\t\022\036\n\004data\030\003 \003(\0132\020" +
      ".Merge.DataEntry\0324\n\tDataEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\026\n\005value\030\002 \001(\0132\007.Record:\0028\001\"y\n\010Checks" +
      "um\022\r\n\005group\030\001 \001(\t\022\016\n\006origin\030\002 \001(\t\022!\n\004dat" +
      "a\030\003 \003(\0132\023.Checksum.DataEntry\032+\n\tDataEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"4\n\005Que" +
      "ry\022\r\n\005group\030\001 \001(\t\022\016\n\006origin\030\002 \001(\t\022\014\n\004key" +
      "s\030\003 \003(\t\"~\n\006Values\022\r\n\005group\030\001 \001(\t\022\016\n\006orig" +
      "in\030\002 \001(\t\022\037\n\004data\030\003 \003(\0132\021.Values.DataEntr" +
      "y\0324\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\026\n\005value\030\002 \001" +
      "(\0132\007.Record:\0028\001\"*\n\010Response\022\r\n\005group\030\001 \001" +
      "(\t\022\017\n\007success\030\002 \001(\0102\217\001\n\rDistroService\022\032\n" +
      "\004load\022\005.Load\032\007.Values\"\0000\001\022\033\n\004send\022\006.Merg" +
      "e\032\t.Response\"\000\022%\n\007receive\022\t.Checksum\032\t.R" +
      "esponse\"\000(\0010\001\022\036\n\005query\022\006.Query\032\007.Values\"" +
      "\000(\0010\001B2\n.com.alibaba.nacos.core.distribu" +
      "ted.distro.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Record_descriptor,
        new String[] { "Data", "CheckSum", });
    internal_static_Load_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Load_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Load_descriptor,
        new String[] { });
    internal_static_Merge_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Merge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Merge_descriptor,
        new String[] { "Group", "Origin", "Data", });
    internal_static_Merge_DataEntry_descriptor =
      internal_static_Merge_descriptor.getNestedTypes().get(0);
    internal_static_Merge_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Merge_DataEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Checksum_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Checksum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Checksum_descriptor,
        new String[] { "Group", "Origin", "Data", });
    internal_static_Checksum_DataEntry_descriptor =
      internal_static_Checksum_descriptor.getNestedTypes().get(0);
    internal_static_Checksum_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Checksum_DataEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Query_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Query_descriptor,
        new String[] { "Group", "Origin", "Keys", });
    internal_static_Values_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Values_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Values_descriptor,
        new String[] { "Group", "Origin", "Data", });
    internal_static_Values_DataEntry_descriptor =
      internal_static_Values_descriptor.getNestedTypes().get(0);
    internal_static_Values_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Values_DataEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "Group", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
