// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface LoadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Load)
    com.google.protobuf.MessageOrBuilder {
}
