// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface MergeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Merge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>string origin = 2;</code>
   */
  String getOrigin();
  /**
   * <code>string origin = 2;</code>
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>map&lt;string, .Record&gt; data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, .Record&gt; data = 3;</code>
   */
  boolean containsData(String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Record>
  getData();
  /**
   * <code>map&lt;string, .Record&gt; data = 3;</code>
   */
  java.util.Map<String, Record>
  getDataMap();
  /**
   * <code>map&lt;string, .Record&gt; data = 3;</code>
   */

  Record getDataOrDefault(String key, Record defaultValue);
  /**
   * <code>map&lt;string, .Record&gt; data = 3;</code>
   */

  Record getDataOrThrow(String key);
}
