// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface QueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Query)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   * if keys is empty, mean query all
   * </pre>
   *
   * <code>string origin = 2;</code>
   */
  String getOrigin();
  /**
   * <pre>
   * if keys is empty, mean query all
   * </pre>
   *
   * <code>string origin = 2;</code>
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>repeated string keys = 3;</code>
   */
  java.util.List<String>
      getKeysList();
  /**
   * <code>repeated string keys = 3;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 3;</code>
   */
  String getKeys(int index);
  /**
   * <code>repeated string keys = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
