// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string checkSum = 2;</code>
   */
  String getCheckSum();
  /**
   * <code>string checkSum = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheckSumBytes();
}
