// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Distro.proto

package com.alibaba.nacos.core.distributed.distro.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   * if keys is empty, mean query all
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  java.util.List<String>
      getKeysList();
  /**
   * <pre>
   * if keys is empty, mean query all
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  int getKeysCount();
  /**
   * <pre>
   * if keys is empty, mean query all
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  String getKeys(int index);
  /**
   * <pre>
   * if keys is empty, mean query all
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);

  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */
  int getExtendInfoCount();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */
  boolean containsExtendInfo(String key);
  /**
   * Use {@link #getExtendInfoMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getExtendInfo();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */
  java.util.Map<String, String>
  getExtendInfoMap();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */

  String getExtendInfoOrDefault(String key, String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extendInfo = 3;</code>
   */

  String getExtendInfoOrThrow(String key);
}
